title: Sto's thoughts
author: David Stosik

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  style: compressed

kramdown:
  header_offset: 1

include:
  - .nojekyll

exclude:
  - README.md

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
