title: Sto's thoughts
author: David Stosik

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  style: compressed

include:
  - .nojekyll

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
