# Site settings
title: David Stosik
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm David Stosik, develop websites on my day job, and sometimes write code on
  my free time too. I'll use this space to share my experiences and thoughts.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://davidstosik.github.io" # the base hostname & protocol for your site
twitter_username: davidstosik
github_username:  davidstosik

# Build settings
markdown: kramdown

highlighter: pygments

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "David Stosik"
      comments: true
      social: true
