name: Build Bridgetown site

on: pull_request

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version-file: ".node-version"
          cache: "npm"

      - name: Install Node dependencies
        run: npm ci

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v6

      - name: Build with Bridgetown
        run: bin/bridgetown deploy
        env:
          BRIDGETOWN_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: output
