name: Build Bridgetown site

on: pull_request

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "21"
          cache: "yarn"

      - name: Install Yarn dependencies
        run: yarn install --frozen-lockfile

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2

      - name: Build with Bridgetown
        run: bin/bridgetown deploy
        env:
          BRIDGETOWN_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: output
